language: python
# using system site packages only works with 2.7 and 3.5
python:
    # - "2.6"
    - "2.7"
    - "3.5"
    # - "3.3"
    # - "3.4"
virtualenv:
    system_site_packages: true
# install scipy and numpy for python2 and python3
before_install
    - sudo apt-key update
    - sudo apt-get update -q
    - sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
    - sudo apt-get -y install build-essential
    - sudo apt-get -y --force-yes install linux-headers-`uname -r`
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shmall:
    - sudo apt-get install python-numpy python-scipy python3-numpy python3-scipy
    - pip install coverage
# install dependencies
    - pip install -e .
# command to run tests
script:
    - nosetests --with-cover --cover-package=ecos src/test_interface.py src/test_interface_bb.py
